name: Download from Localazy
on: 
  push:
    # we want to pull from localazy only with a new version
    # tags:
    # - 'v*'

jobs:
  localazy-download-test:
    name: Download strings from Localazy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: localazy/download@v1
        with:
          read_key: ${{ secrets.LOCALAZY_READ_KEY }}
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}

      - run: |
          # Test that localized files were downloaded by listing 
          # the content of langs folders.
          ls langs/**/*.lang

      - uses: EndBug/add-and-commit@v7
        with:
          pull_strategy: NO-PULL
          default_author: github_actions
