name: Download from Localazy
on: 
  push:
    # only pull for develop branch
    branches: [ develop ]
    # we want to pull from localazy only with a new version
    # tags:
    # - 'v*'

jobs:
  localazy-download-test:
    name: Download strings from Localazy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: localazy/download@v1
        with:
          read_key: ${{ secrets.LOCALAZY_READ_KEY }}
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}

      - run: |
          # Test that localized files were downloaded by listing 
          # the content of langs folders.
          pwd
          ls langs/**/*.lang

      - uses: EndBug/add-and-commit@v7
        with:
          author_name: 
          pull_strategy: NO-PULL
          default_author: github_actions
          add: . #langs/\*.lang
